### ISSUE TITLE
License for portforward.c

### ISSUE THREAD

**Issue by fidian** [antialize/utils#1]
There's no license information in portforward.c.  It nearly perfectly addresses a problem of mine.  A few minor modifications are required to do what I need, but your code would provide a solid base.

Is there any way you could license this code or tell me what you indent to license it under?  MIT?  GPL?  Public domain?

**Comment by antialize** [comment]
I added a license.txt. You can choose whatever licenses you want.

**Comment by fidian** [comment]
That works for me.  Thanks!

**Comment by fidian** [comment]
In case you were wondering how I was going to use this:  https://github.com/fidian/tcp-port-forward
